skinparam backgroundColor  white
skinparam activityArrowColor  #41535C
skinparam activityBackgroundColor  white
skinparam activityBorderColor  #41535C
skinparam activityStartColor  black
skinparam activityEndColor  black
skinparam activityBarColor  black
skinparam actorBackgroundColor  white
skinparam actorBorderColor  #41535C
skinparam usecaseArrowColor  #41535C
skinparam usecaseBackgroundColor  white
skinparam usecaseBorderColor  #41535C
skinparam classArrowColor  #41535C
skinparam classBackgroundColor  white
skinparam classBorderColor  #41535C
skinparam objectArrowColor  #41535C
skinparam objectBackgroundColor  white
skinparam objectBorderColor  #41535C
skinparam packageBackgroundColor  white
skinparam packageBorderColor  #41535C
skinparam stereotypeCBackgroundColor  #5D8630
skinparam stereotypeABackgroundColor  #4275AD
skinparam stereotypeIBackgroundColor  #8F4C6A
skinparam stereotypeEBackgroundColor  #DF682D
skinparam componentArrowColor  #41535C
skinparam componentBackgroundColor  white
skinparam componentBorderColor  #41535C
skinparam componentInterfaceBackgroundColor  white
skinparam componentInterfaceBorderColor  #41535C
skinparam noteBackgroundColor  #FBFB77
skinparam noteBorderColor  #41535C
skinparam stateBackgroundColor  white
skinparam stateBorderColor  #41535C
skinparam stateArrowColor  #41535C
skinparam stateStartColor  black
skinparam stateEndColor  black
skinparam sequenceArrowColor  #41535C
skinparam sequenceDividerBackgroundColor  #EEEEEE
skinparam sequenceGroupBackgroundColor  #EEEEEE
skinparam sequenceLifeLineBackgroundColor  white
skinparam sequenceLifeLineBorderColor  #41535C
skinparam sequenceParticipantBackgroundColor  white
skinparam sequenceParticipantBorderColor  #41535C
skinparam sequenceBoxLineColor  #41535C
skinparam sequenceBoxBackgroundColor  #DDDDDD
skinparam activityFontColor  black
skinparam activityFontSize   14
skinparam activityFontStyle   plain
skinparam activityFontName Ricty
skinparam activityArrowFontColor  black
skinparam activityArrowFontSize   13
skinparam activityArrowFontStyle   plain
skinparam activityArrowFontName Ricty
skinparam circledCharacterFontColor  circledCharacterRadius
skinparam circledCharacterFontSize   black
skinparam circledCharacterFontStyle   17
skinparam circledCharacterFontName Ricty
skinparam classArrowFontColor  black
skinparam classArrowFontSize   10
skinparam classArrowFontStyle   plain
skinparam classArrowFontName Ricty
skinparam classAttributeFontColor  classAttributeFontName Ricty
skinparam classAttributeFontSize   black
skinparam classAttributeIconSize   10
skinparam classAttributeFontStyle
skinparam classFontColor  black
skinparam classFontSize   12
skinparam classFontStyle   plain
skinparam classFontName Ricty
skinparam classStereotypeFontColor  black
skinparam classStereotypeFontSize   12
skinparam classStereotypeFontStyle   italic
skinparam classStereotypeFontName Ricty
skinparam objectArrowFontColor  black
skinparam objectArrowFontSize   10
skinparam objectArrowFontStyle   plain
skinparam objectArrowFontName Ricty
skinparam objectAttributeFontColor  black
skinparam objectAttributeFontSize   10
skinparam objectAttributeFontStyle   plain
skinparam objectAttributeFontName Ricty
skinparam objectFontColor  black
skinparam objectFontSize   12
skinparam objectFontStyle   plain
skinparam objectFontName Ricty
skinparam objectStereotypeFontColor  black
skinparam objectStereotypeFontSize   12
skinparam objectStereotypeFontStyle   italic
skinparam objectStereotypeFontName Ricty
skinparam componentFontColor  black
skinparam componentFontSize   14
skinparam componentFontStyle   plain
skinparam componentFontName Ricty
skinparam componentStereotypeFontColor  black
skinparam componentStereotypeFontSize   14
skinparam componentStereotypeFontStyle   italic
skinparam componentStereotypeFontName Ricty
skinparam componentArrowFontColor  black
skinparam componentArrowFontSize   13
skinparam componentArrowFontStyle   plain
skinparam componentArrowFontName Ricty
skinparam noteFontColor  black
skinparam noteFontSize   13
skinparam noteFontStyle   plain
skinparam noteFontName Ricty
skinparam packageFontColor  black
skinparam packageFontSize   14
skinparam packageFontStyle   plain
skinparam packageFontName Ricty
skinparam sequenceActorFontColor  black
skinparam sequenceActorFontSize   13
skinparam sequenceActorFontStyle   plain
skinparam sequenceActorFontName Ricty
skinparam sequenceDividerFontColor  black
skinparam sequenceDividerFontSize   13
skinparam sequenceDividerFontStyle   bold
skinparam sequenceDividerFontName Ricty
skinparam sequenceArrowFontColor  black
skinparam sequenceArrowFontSize   13
skinparam sequenceArrowFontStyle   plain
skinparam sequenceArrowFontName Ricty
skinparam sequenceGroupFontColor  black
skinparam sequenceGroupFontSize   11
skinparam sequenceGroupFontStyle   bold
skinparam sequenceGroupFontName Ricty
skinparam sequenceGroupHeaderFontColor  black
skinparam sequenceGroupHeaderFontSize   13
skinparam sequenceGroupHeaderFontStyle   bold
skinparam sequenceGroupHeaderFontName Ricty
skinparam sequenceParticipantFontColor  black
skinparam sequenceParticipantFontSize   13
skinparam sequenceParticipantFontStyle   plain
skinparam sequenceParticipantFontName Ricty
skinparam sequenceStereotypeFontColor  black
skinparam sequenceStereotypeFontSize   14
skinparam sequenceStereotypeFontStyle   italic
skinparam sequenceStereotypeFontName Ricty
skinparam sequenceTitleFontColor  black
skinparam sequenceTitleFontSize   13
skinparam sequenceTitleFontStyle   bold
skinparam sequenceTitleFontName Ricty
skinparam titleFontColor  black
skinparam titleFontSize   18
skinparam titleFontStyle   plain
skinparam titleFontName Ricty
skinparam stateFontColor  black
skinparam stateFontSize   14
skinparam stateFontStyle   plain
skinparam stateFontName Ricty
skinparam stateArrowFontColor  black
skinparam stateArrowFontSize   13
skinparam stateArrowFontStyle   plain
skinparam stateArrowFontName Ricty
skinparam stateAttributeFontColor  black
skinparam stateAttributeFontSize   12
skinparam stateAttributeFontStyle   plain
skinparam stateAttributeFontName Ricty
skinparam usecaseFontColor  black
skinparam usecaseFontSize   14
skinparam usecaseFontStyle   plain
skinparam usecaseFontName Ricty
skinparam usecaseStereotypeFontColor  black
skinparam usecaseStereotypeFontSize   14
skinparam usecaseStereotypeFontStyle   italic
skinparam usecaseStereotypeFontName Ricty
skinparam usecaseActorFontColor  black
skinparam usecaseActorFontSize   14
skinparam usecaseActorFontStyle   plain
skinparam usecaseActorFontName Ricty
skinparam usecaseActorStereotypeFontColor  black
skinparam usecaseActorStereotypeFontSize   14
skinparam usecaseActorStereotypeFontStyle   italic
skinparam usecaseActorStereotypeFontName Ricty
skinparam usecaseArrowFontColor  black
skinparam usecaseArrowFontSize   13
skinparam usecaseArrowFontStyle   plain
skinparam usecaseArrowFontName Ricty
skinparam footerFontColor  black
skinparam footerFontSize   10
skinparam footerFontStyle   plain
skinparam footerFontName Ricty
skinparam headerFontColor  black
skinparam headerFontSize   10
skinparam headerFontStyle   plain
skinparam headerFontName Ricty
