[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kchmck/vim-coffee-script'


[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'ruby.vim'

[[plugins]]
repo = 'QuickBuf'

[[plugins]]
repo = 'neocomplcache'

[[plugins]]
repo = 'xterm16.vim'

[[plugins]]
repo = 'python.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'suan/vim-instant-markdown'

[[plugins]]
repo = 'rizzatti/funcoo.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdtree'
