#!/bin/bash -x


SCRIPTS_DIR='scripts'
DOCS_DIR='docs'
SRC_DIR='src'
ETC_DIR='etc'

mkdir $SCRIPTS_DIR
mkdir $DOCS_DIR
mkdir	$SRC_DIR
mkdir	$ETC_DIR


touch .gitignore
touch .dockerignore

echo 'vendor/bundle' >> .gitignore
echo 'node_modules' >> .gitignore
echo '.idea' >> .gitignore
echo '.DS_Store' >> .gitignore

SCRIPT_DEFAULT_CODES='#!/bin/sh -xe  \n
CURRENT=$(cd $(dirname $0) && pwd)  \n
cd $CURRENT/../src  \n
'

echo -e $SCRIPT_DEFAULT_CODES > scripts/bootstrap
echo -e $SCRIPT_DEFAULT_CODES > scripts/ci-build
echo -e $SCRIPT_DEFAULT_CODES > scripts/ci-deploy
echo -e $SCRIPT_DEFAULT_CODES > scripts/server
echo -e $SCRIPT_DEFAULT_CODES > scripts/console
echo -e $SCRIPT_DEFAULT_CODES > scripts/test
echo -e $SCRIPT_DEFAULT_CODES > scripts/build
echo -e $SCRIPT_DEFAULT_CODES > scripts/migrate

chmod +x scripts/*

initReadme

echo 'Created!'
tree

