#!/bin/bash
open_remote(){
  open https://nishimuuu.itemo.recruit-jinji.jp/jupyter
  exit
}

run_local(){
  docker run -P -d -v $(pwd):/home/jovyan/local nishimuuu/jupyter
  sleep 2
  port=$(docker ps -n 1 --format "{{.Ports}}" | sed 's/->.*\(tcp\)//' | sed 's/^.*://g')
  open http://localhost:$port
}


while getopts r OPT
do
  case $OPT in
    r)  open_remote
      ;;
  esac
done

run_local


